version: "2"

services:
    cms-xmr:
        image: xibosignage/xibo-xmr:release_1.8.0-rc2
        ports:
            - "9505:9505"
        restart: always
        env_file: config.env
        mem_limit: 256m
    cms-web:
        image: xibosignage/xibo-cms:develop
        volumes:
            - "${DATA_DIR}/shared/cms/custom:/var/www/cms/custom"
            - "${DATA_DIR}/shared/backup:/var/www/backup"
            - "${DATA_DIR}/shared/cms/web/theme/custom:/var/www/cms/web/theme/custom"
            - "${DATA_DIR}/shared/cms/library:/var/www/cms/library"
            - "${DATA_DIR}/shared/cms/web/userscripts:/var/www/cms/web/userscripts"
        restart: always
        links:
            - cms-xmr:50001
        environment:
            - XMR_HOST=cms-xmr
        ports:
            - "80:80"
        env_file: config.env
        mem_limit: 1g

