version: "2"

services:
    cms-xmr:
        environment:
            - DEBUG: "true"
    cms-web:
        image: xibosignage/xibo-cms-dev:develop
        volumes:
            - "${DATA_DIR}/shared/web:/var/www/cms"
        links:
            - cms-db:mysql
            - cms-xmr:50001
